services:
  hugo:
    image: ghcr.io/hugomods/hugo:ci-0.128.0
    command: hugo server --bind 0.0.0.0 --buildDrafts --disableFastRender
    volumes:
      - .:/src
    ports:
      - "1313:1313"
    environment:
      - HUGO_WATCH=true
