[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.123.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  # Native cache dir - no plugin needed
  HUGO_CACHEDIR = "/opt/build/cache/hugo"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture --buildDrafts"

[context.branch-deploy]
  command = "hugo --gc --minify --buildFuture"
